# Generated by Django 2.0.1 on 2018-01-27 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hazard_lvl',
            field=models.CharField(choices=[('Критический', 'Критический'), ('Высокий', 'Высокий'), ('Средний', 'Средний'), ('Низкий', 'Низкий')], default='Средний', max_length=25, verbose_name='Уровень опасности'),
        ),
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
