# Generated by Django 2.0.1 on 2018-01-28 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0003_auto_20180128_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionCallEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapi.Event')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.Division', verbose_name='Взвод')),
            ],
            options={
                'verbose_name': 'Вызов взвода',
                'verbose_name_plural': 'Вызовы взводов',
            },
            bases=('webapi.event',),
        ),
    ]
